### ISSUE TITLE
default_max_tokens= mechanism doesn't look right to me

### ISSUE THREAD

**Issue by simonw** [hex/llm-perplexity#5]
This mechanism: https://github.com/hex/llm-perplexity/blob/acb4a5d202bd994e4a0e5108c63f89731c80a0dd/llm_perplexity.py#L6-L9

Also: https://github.com/hex/llm-perplexity/blob/acb4a5d202bd994e4a0e5108c63f89731c80a0dd/llm_perplexity.py#L57-L64

I don't think setting a default like this is the right thing to do. The Perplexity API's max tokens option, though vaguely documented, refers to the maximum number of _output_ tokens that the model should return. The default values set in the code here look to be the total context length of the model, including input tokens.

Most models such as Claude 3 and GPT-4 have much tighter restrictions on their output tokens - gpt-4-turbo allows 128,000 input tokens but only a maximum of 4,096 output tokens ([docs](https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4)). Likewise, Claude 3 models allow 200,000 tokens but also [only 4,096 output tokens](https://docs.anthropic.com/claude/docs/models-overview#model-comparison).

Perplexity don't currently document the max output tokens for the model. Since it's not documented, I think the best approach is not to attempt to enforce it within the LLM plugin at all - let users set any number they like and trust the Perplexity API to return an error if they set an invalid number.

**Comment by hex** [comment]
Not enforcing the max_tokens seems to be the right approach in this case. Thanks, Simon!
