### ISSUE TITLE
Feature Request: Add Support for Llama 3.3

### ISSUE THREAD

**Issue by hcal** [hex/llm-perplexity#9]
**Description**:  
Perplexity now offers Llama 3.3, and it would be great to include this model in the project.

**Suggested Solution**:  
The following modification successfully registers the new model:  
Add this line to the `register_models(register):` function in `/llm_perplexity.py`:
```
register(Perplexity("llama-3.3-70b-instruct"))
```

**Next Steps**:  
I’d like to learn how to submit a pull request, but in the meantime, this quick change works and can be reviewed for implementation.

**Comment by hex** [comment]
Thanks for the heads up, it seems that the [API docs](https://docs.perplexity.ai/guides/model-cards) are not updated yet. Add llama-3.3-70b-instruct support in the 2024.12.0 version. Cheers!
